const express = require('express')
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
require('dotenv').config()
const locationController = require('./locations/locations.controller')
const usersController = require('./users/users.controller')
const app = express()
const port = 3000

app.use(bodyParser.json())
app.use(locationController)
app.use(usersController)
app.get("/", (req, res) => {
	return res.status(200).send("Hello World")
})
app.listen(port, async () => {
	await mongoose.connect(process.env.MONGO_URI)
	//const User1 = new Users({username:"Adrien",password:"123"})
	//const User2 = new Users({username:"Loulou",password:"uoluoL"})
	//const User3 = new Users({username:"Toto",password:"Toto123"})
	//await User1.save()
	//await User2.save()
	//await User3.save()
	console.log("Connected")
	console.log(`API listening on port ${port}, visit http://localhost:${port}/`)
})
